name: CI

on:
  push:                       # будь-яка гілка -> тести (build)
  pull_request:
    branches: [ main ]        # PR у main -> тести + деплой у staging

# Найменші привілеї за замовчуванням для GITHUB_TOKEN
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Publish
        run: dotnet publish src/Api/Api.csproj --no-build --configuration Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-${{ github.run_number }}
          path: ./publish
          retention-days: 7

  # PR у main -> деплой у STAGING (глянути зміну наживо ДО мерджу)
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: staging
      url: https://cicd-stage-a2b0a2huc2hwcea2.polandcentral-01.azurewebsites.net/weatherforecast
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-${{ github.run_number }}
          path: ./publish

      - name: Deploy to Azure (staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: cicd-stage
          publish-profile: ${{ secrets.STAGE }}
          package: ./publish

  # Мердж (push) у main -> деплой у PRODUCTION
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://cicd-deploy-cpa0a4g9ckgae3g8.polandcentral-01.azurewebsites.net/weatherforecast
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-${{ github.run_number }}
          path: ./publish

      - name: Deploy to Azure (production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: cicd-deploy
          publish-profile: ${{ secrets.DEPLOY }}
          package: ./publish
